# Generated by Django 2.2.2 on 2019-06-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190621_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutrition_grades',
        ),
    ]
