# Generated by Django 2.2.2 on 2019-06-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20190622_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='substitutes',
            field=models.ManyToManyField(related_name='_product_substitutes_+', to='search.Product'),
        ),
    ]
