# Generated by Django 2.2.2 on 2019-06-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('brands', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('product_url', models.CharField(max_length=150, null=True)),
                ('product_code', models.CharField(max_length=20, null=True)),
                ('product_image', models.CharField(max_length=100, null=True)),
                ('nutriscore', models.CharField(max_length=1, null=True)),
                ('stores', models.CharField(max_length=150, null=True)),
                ('quantity', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
