# Generated by Django 2.2.2 on 2019-06-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
